site_name: Konstantin Ryabtsev

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: blue
  features: []

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

plugins: []

extra:
  generator: false
